// config.example.js - ESTE ARQUIVO VAI PARA O GITHUB
const CONFIG = {
    SUPABASE_URL: 'COLOQUE_SUA_URL_AQUI',
    SUPABASE_KEY: 'COLOQUE_SUA_CHAVE_AQUI',
    GEMINI_KEY: 'COLOQUE_SUA_CHAVE_GEMINI_AQUI'
};
